// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uccamxnhjbdobqshlwun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjY2FteG5oamJkb2Jxc2hsd3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjU5NDQsImV4cCI6MjA2NTkwMTk0NH0.UTPdqndQeIa1z536_7sGtoki23_x0pPt5xAJGLwyvso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);